# Generated by Django 5.2 on 2025-04-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
