# Generated by Django 5.2 on 2025-04-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
