# Generated by Django 5.2 on 2025-04-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
