# Generated by Django 5.2 on 2025-04-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_order_items_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
