# Generated by Django 5.2 on 2025-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_order_items_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='time',
            field=models.JSONField(default=dict),
        ),
    ]
