# Generated by Django 5.2 on 2025-04-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_ingredient_remove_dish_ingredients_dish_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
