# Generated by Django 5.2 on 2025-04-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_dish_ingredients'),
        ('restaurant', '0007_remove_dish_ingredients_dish_ingredients'),
    ]

    operations = [
    ]
