# Generated by Django 5.2 on 2025-04-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_merge_20250417_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='time',
        ),
    ]
