# Generated by Django 5.2 on 2025-04-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_ingredient_dish_time_remove_dish_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
    ]
